name: Add/Fix/Feat Request
description: "Request to add, fix, or enhance a feature in the project"
title: "[ADD/FIX/FEAT]: "
labels:
  - enhancement
  - bug
  - feature request
  - tool request
  - documentation
  - Ideas/Feedback
  - help wanted
  - question
  - tools install/update
  - vulnerability
  - Will Push to Main
  - wontfix
  - good first issue
  - invalid
  - duplicate
  - Feature
  - game changer
assignees:
  - RAJANAGORI
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to this project!  
        Please fill out the following details to help us address your request effectively.

  - type: dropdown
    id: request_type
    attributes:
      label: Type of Request
      description: "Select whether this is an Add, Fix, or Feat request."
      options:
        - Add (Adding a new feature or component)
        - Fix (Resolving a bug or issue)
        - Feat (Enhancing or improving an existing feature)
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Title
      description: "Enter a concise title summarizing your request."
      placeholder: "e.g., Add user authentication module"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Provide a clear and detailed description of your request."
      placeholder: "Describe the issue, feature, or improvement."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: "How important is this request?"
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: dropdown
    id: applicable_label
    attributes:
      label: Label
      description: "Select the most applicable label for this issue."
      options:
        - bug - Something isn't working
        - documentation - Improvements or additions to documentation
        - duplicate - This issue or pull request already exists
        - enhancement - New feature or request
        - Feature - New Feature in Process
        - game changer - Out of the Box
        - good first issue - Good for newcomers
        - help wanted - Extra attention is needed
        - Ideas/Feedback - Add valuable ideas or feedback
        - invalid - This doesn't seem right
        - question - Further information is requested
        - tool request - Suggest adding a new tool
        - tools install/update - Install or update tools to the latest version
        - vulnerability - Issues or vulnerabilities that need review
        - Will Push to Main - Dev code is under testing and will push to the main branch
        - wontfix - This will not be worked on
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: "Provide a brief summary of the solution or implementation approach."
      placeholder: "e.g., Add a login page and integrate JWT authentication."

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: "Include any extra details, screenshots, or references."
      placeholder: "Add any additional context here."

  # Uncomment this section if you want to enforce acknowledgment of contribution guidelines
  - type: checkboxes
    id: contribution_guidelines
    attributes:
      label: Contribution Guidelines
      description: "By submitting this request, you agree to follow the project's contribution guidelines."
      options:
        - label: I have read and agree to the contribution guidelines.
          required: true
