{{- if .Values.ingress.enabled}}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
  name: {{ .Release.Name }}-ingress
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  {{- if .Values.ingress.host.enabled}}
  - host: {{ .Values.ingress.host.name }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.service.port }}
  {{- else}}
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.service.port }}
  {{- end}}
  {{- if .Values.ingress.tls.enabled}}
  tls:
  - hosts:
    - {{ .Values.ingress.host.name }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end}}
{{- end}}