kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: nightingale
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7681
  selector:
    app: nightingale