name: Anchore Grype Vulnerability Scan

on:
  push:
    branches: ["development"]
    paths:
      - "Dockerfiles/*.Dockerfile"
      - "Dockerfile"
  pull_request:
    branches: ["development"]
    paths:
      - "Dockerfiles/*.Dockerfile"
      - "Dockerfile"
      - ".github/workflows/anchore.yml"

jobs:
  Anchore-Build-Scan:
    permissions:
      contents: read   # For actions/checkout to fetch code
      security-events: write   # For uploading SARIF results
      actions: read   # Only required for a private repository
    runs-on: self-hosted
    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Cache Grype DB
      uses: actions/cache@v3
      with:
        path: ~/.cache/grype/db
        key: ${{ runner.os }}-grype-db-${{ github.sha }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest

    - name: Run the Anchore Grype scan action
      uses: anchore/scan-action@v2
      id: scan
      with:
        image: "localbuild/testimage:latest"
        grype-version: 0.77.4
        fail-build: true
        severity-cutoff: high  # Adjusted from "critical" to "high"

    - name: Set SARIF output using environment file
      run: echo "sarif_file=${{ steps.scan.outputs.sarif }}" >> $GITHUB_ENV

    - name: Upload vulnerability report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ env.sarif_file }}
