name: Anchore Grype vulnerability scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Anchore-Build-Scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: self-hosted
    steps:
    - name: Set up Docker in WSL 2
      run: |
        if ! command -v docker &> /dev/null; then
          echo "Docker not found, installing..."
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          sudo usermod -aG docker $USER
          newgrp docker
        fi
    - name: Check out the code
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: echo "raja" | sudo -S apt-get install docker -y && sudo docker build . --file Dockerfile --tag localbuild/testimage:latest
    - name: Run the Anchore Grype scan action
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: "localbuild/testimage:latest"
        grype-version: 0.77.4
        fail-build: true
        severity-cutoff: critical
    - name: Upload vulnerability report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}