name: Anchore Grype vulnerability scan

on:
  push:
    branches: [ "development" ]
    paths:
      - "Dockerfiles/*.Dockerfile"
      - "Dockerfile"
      - ".github/workflows/anchore.yml"
  pull_request:
    branches: [ "development" ]
    paths:
      - "Dockerfiles/*.Dockerfile"
      - "Dockerfile"
      - ".github/workflows/anchore.yml"

jobs:
  Anchore-Build-Scan:
    permissions:
      contents: read
      security-events: write
    runs-on: self-hosted
    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Cache Grype DB
      uses: actions/cache@v3
      with:
        path: ~/.cache/grype/db
        key: ${{ runner.os }}-grype-db-${{ github.sha }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest

    - name: Run the Anchore Grype scan action
      uses: anchore/scan-action@v2
      id: scan
      with:
        image: "localbuild/testimage:latest"
        grype-version: 0.80.0
        fail-build: true

    - name: Upload vulnerability report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
        category: "Grype Scan"