name: Docker Image Delete

on:
  push:
    branches: [development]
    paths:
      - ".github/workflows/docker-image-list-copy.yaml"
  pull_request:
    branches: [development]
    paths:
      - ".github/workflows/docker-image-list-copy.yaml"

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAMES: |
    nightingale_web_vapt_image
    nightingale_wordlist_image
    nightingale_network_vapt_image
    nightingale_forensic_and_red_teaming
    nightingale_osint_tools_image
    nightingale_mobile_vapt_image
    nightingale
    nightingale_programming_image

jobs:
  delete-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: [
          nightingale_web_vapt_image,
          nightingale_wordlist_image,
          nightingale_network_vapt_image,
          nightingale_forensic_and_red_teaming,
          nightingale_osint_tools_image,
          nightingale_mobile_vapt_image,
          nightingale,
          nightingale_programming_image
        ]
    steps:
    - name: Github Login
      env:
        GITHUB_TOKEN: ${{secrets.TOKEN}}
      run: |
        echo "${{secrets.TOKEN}}" | docker login ghcr.io -u ${{secrets.USERNAME}} --password-stdin
    
    - name: List Docker Images
      run: |
        docker images
        
    - name: Install dateparser
      run: |
        pip install dateparser

    - name: Run Python code
      run: |
        import dateparser
        cut_off = dateparser.parse ('One week ago', settings={'TIMEZONE': 'UTC'})
        print(f"::set-env name=CUT_OFF::{cut_off}")
      shell: python

    - name: Delete old images
      uses: snok/container-retention-policy@v2
      with:
        image-names: ${{ matrix.image-name }}
        cut-off: ${{ env.CUT_OFF }}
        keep-at-least: 3
        filter-tags: "stable, linux-amd64, linux-arm64, unstable, development"
        account-type: personal
        token: ${{secrets.TOKEN}}
