name: Docker Image CI

on:
  push:
    branches: [ main ]
    # paths:
    #   - 'Dockerfiles/*'
    #   - 'Dockerfile'
  pull_request:
    branches: [ main ]
    # paths:
    #   - 'Dockerfiles/*'
    #   - 'Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: docker build for programming language image
      run: docker build . --file Dockerfiles/programming_langauge.Dockerfile --tag rajanagori/nightingale_programming_image:v1

    - name : docker push programming language image
      run: docker push rajanagori/nightingale_programming_image:v1

    - name: Build the Docker image and push it to docker hub for Final Nightingale image 
      run: docker build . --file Dockerfile --tag rajanagori/nightingale:latest
      
    - name: Docker Push
      run: docker push rajanagori/nightingale:latest