name: Publish Docker Image
on: push
jobs:
  docker:
    runs-on: debian-latest
    name: Build Docker image of Nightingale on Docker Hub
    steps:
      - name: Publish to Github Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{github.repository}}/nightingale
          tags: latest, ${{ github.run_number }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: rajanagori/nightingale
          tags: latest, ${{ github.run_number }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: latest, ${{ github.run_number }}