name: Docker Image Delete

on:
  push:
    branches: [development]
    paths:
      - ".github/workflows/docker-image-list copy"
  pull_request:
    branches: [development]
    paths:
      - ".github/workflows/docker-image-list copy"

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAMES: |
    nightingale_web_vapt_image
    nightingale_wordlist_image
    nightingale_network_vapt_image
    nightingale_forensic_and_red_teaming
    nightingale_osint_tools_image
    nightingale_mobile_vapt_image
    nightingale
    nightingale_programming_image

jobs:
  delete-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: ${{ fromJson(env.IMAGE_NAMES) }}
    steps:
    - name: Github Login
      env:
        GITHUB_TOKEN: ${{secrets.TOKEN}}
      run: |
        echo "${{secrets.TOKEN}}" | docker login ghcr.io -u ${{secrets.USERNAME}} --password-stdin
    
    - name: List Docker Images
      run: |
        docker images
        
    - name: Delete old images
      uses: snok/container-retention-policy@v2
      with:
        image-names: ${{ matrix.image-name }}
        cut-off: One week ago
        keep-at-least: 3
        filter-tags: "development, linux_amd64_development, darwin_x86-64_development, darwin_amd64_development"
        account-type: personal
        token: ${{secrets.TOKEN}}