name: Remove Docker Images

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Github Login
      env:
        GITHUB_TOKEN: ${{secrets.TOKEN}}
      run: |
        echo "${{secrets.TOKEN}}" | docker login ghcr.io -u ${{secrets.USERNAME}} --password-stdin
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: List Docker Images
      run: |
        docker images

    # - name: Container Retention Policy
    #   uses: snok/container-retention-policy@v2.1.2
    #   with:
    #     image-names: stable, linux-amd64, linux-arm64, unstable
    #     keep-at-least: 3
    #     token: ${{secrets.TOKEN}}
    - uses: smartsquaregmbh/delete-old-packages@v0.7.0
      with:
        type: docker
        keep: 2
        names: |
          nightingale_web_vapt_image
          nightingale_wordlist_image
          nightingale_network_vapt_image
          nightingale_forensic_and_red_teaming
          nightingale_osint_tools_image
          nightingale_mobile_vapt_image
          nightingale
          nightingale_programming_image
              