name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfiles/*'
      - 'Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfiles/*'
      - 'Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: | 
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: docker build for programming language image  
      run: docker build . --file Dockerfiles/programming_langauge.Dockerfile --tag rajanagori/nightingale_programming_image:v1

    - name: Pushing the docker image
      run: docker push rajanagori/nightingale_programming_image:v1

    - name: docker build for forensics image  
      run: docker build . --file Dockerfiles/forensics_and_redteam.Dockerfile --tag rajanagori/nightingale_forensic_and_red_teaming:v1.0

    - name: Pushing the docker image
      run: docker push rajanagori/nightingale_forensic_and_red_teaming:v1.0

    - name: docker build for web image  
      run: docker build . --file Dockerfiles/web_vapt.Dockerfile --tag rajanagori/nightingale_web_vapt_image:v1.0

    - name: Pushing the docker image
      run: docker push rajanagori/nightingale_web_vapt_image:v1.0

    - name: docker build for network image  
      run: docker build . --file Dockerfiles/network_vapt.Dockerfile --tag rajanagori/nightingale_network_vapt_image:v1.0

    - name: Pushing the docker image
      run: docker push rajanagori/nightingale_network_vapt_image:v1.0
    
    - name: docker build for osint image  
      run: docker build . --file Dockerfiles/osint_tools.Dockerfile --tag rajanagori/nightingale_osint_image:v1.0

    - name: Pushing the docker image
      run: docker push rajanagori/nightingale_osint_image:v1.0

    - name: docker build for mobile image
      run: docker build . --file Dockerfiles/mobile_vapt.Dockerfile --tag rajanagori/nightingale_mobile_vapt_image:v1.1

    - name: Pushing the docker image
      run: docker push rajanagori/nightingale_mobile_vapt_image:v1.1

    - name: docker build for wordlist image
      run: docker build . --file Dockerfiles/wordlist.Dockerfile --tag rajanagori/nightingale_wordlist_image:v1.0

    - name: Pushing the docker image
      run: docker push rajanagori/nightingale_wordlist_image:v1.0

    - name: Build the Docker image and push it to docker hub for Final Nightingale image
      run: docker build . --file Dockerfile --tag rajanagori/nightingale:development

    - name: Pushing the docker image
      run: docker push rajanagori/nightingale:development