name: Docker Image CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKERFILES_PATH: Dockerfiles
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Github Login
      env:
        GITHUB_TOKEN: ${{secrets.TOKEN}}
      run: |
        echo "${{secrets.TOKEN}}" | docker login ghcr.io -u ${{secrets.USERNAME}} --password-stdin
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    # Build Docker images
    - name: Build nightingale_programming_image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 . --no-cache --file $DOCKERFILES_PATH/programming_langauge.Dockerfile --tag $DOCKER_REGISTRY/rajanagori/nightingale_programming_image:development
    # # Push Docker images
    - name: Push nightingale_programming_image
      run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_programming_image:multiOS"

    - name: Build nightingale_forensic_and_red_teaming
      run: |
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 . --no-cache --file $DOCKERFILES_PATH/forensics_and_redteam.Dockerfile --tag $DOCKER_REGISTRY/rajanagori/nightingale_forensic_and_red_teaming:multiOS
    
    - name: Push nightingale_forensic_and_red_teaming1
      run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_forensic_and_red_teaming:multiOS"
    
    - name: Build nightingale_web_vapt_image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6  . --file $DOCKERFILES_PATH/web_vapt.Dockerfile --tag $DOCKER_REGISTRY/rajanagori/nightingale_web_vapt_image:multiOS
    
    - name: Push nightingale_web_vapt_image
      run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_web_vapt_image:multiOS"
    
    - name: Build nightingale_network_vapt_image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 . --no-cache --file $DOCKERFILES_PATH/network_vapt.Dockerfile --tag $DOCKER_REGISTRY/rajanagori/nightingale_network_vapt_image:multiOS
    
    - name: Push nightingale_network_vapt_image
      run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_network_vapt_image:multiOS"
    
    - name: Build nightingale_osint_image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 . --no-cache --file $DOCKERFILES_PATH/osint_tools.Dockerfile --tag $DOCKER_REGISTRY/rajanagori/nightingale_osint_tools_image:multiOS
    
    - name: Push nightingale_osint_image
      run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_osint_tools_image:multiOS"
    
    - name: Build nightingale_mobile_vapt_image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 . --no-cache --file $DOCKERFILES_PATH/mobile_vapt.Dockerfile --tag $DOCKER_REGISTRY/rajanagori/nightingale_mobile_vapt_image:multiOS
    
    - name: Push nightingale_mobile_vapt_image
      run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_mobile_vapt_image:multiOS"
    
    - name: Build nightingale_wordlist_image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 . --no-cache --file $DOCKERFILES_PATH/wordlist.Dockerfile --tag $DOCKER_REGISTRY/rajanagori/nightingale_wordlist_image:multiOS
    
    - name: Push nightingale_wordlist_image
      run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_wordlist_image:multiOS"
    
    - name: Build nightingale_multiOS_image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 . --no-cache --file Dockerfile --tag $DOCKER_REGISTRY/rajanagori/nightingale:multiOS

    - name: Push nightingale_multiOS_image
      run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale:multiOS"