name: Docker Image CI 

on:
  push:
    branches: [development]
    paths:
      - "Dockerfiles/*.Dockerfile"
      - "Dockerfile"
      - ".github/workflows/docker-image.yaml"
  pull_request:
    branches: [development]
    paths:
      - "Dockerfiles/*.Dockerfile"
      - "Dockerfile"
      - ".github/workflows/docker-image.yaml"

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKERFILES_PATH: Dockerfiles
  IMAGE_NAME: ${{ github.repository }}\
  # Get the short commit SHA
  COMMIT_SHA: ${{ github.sha }}


jobs:
  development:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Github Login
      env:
        GITHUB_TOKEN: ${{secrets.TOKEN}}
      run: |
        echo "${{secrets.TOKEN}}" | docker login ghcr.io -u ${{secrets.USERNAME}} --password-stdin
    - name: Clean Docker build cache
      run: |
        docker buildx prune -f
    
    # Build Docker images
    - name: Build nightingale_programming_image
      run: |
        docker build . --no-cache --file $DOCKERFILES_PATH/programming_langauge.Dockerfile --label branch=development --label commit_sha=$COMMIT_SHA --tag $DOCKER_REGISTRY/rajanagori/nightingale_programming_image:development
    
    # Push Docker images with the same timestamp-based tag
    # - name: Push nightingale_programming_image
    #   run: |
    #     docker push "$DOCKER_REGISTRY/rajanagori/nightingale_programming_image:development"

    - name: Build nightingale_forensic_and_red_teaming
      run: |
        docker build . --no-cache --file $DOCKERFILES_PATH/forensics_and_redteam.Dockerfile --label branch=development --label commit_sha=$COMMIT_SHA --tag $DOCKER_REGISTRY/rajanagori/nightingale_forensic_and_red_teaming:development
    
    # - name: Push nightingale_forensic_and_red_teaming1
    #   run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_forensic_and_red_teaming:development"
    
    - name: Build nightingale_web_vapt_image
      run: |
        docker build  . --file $DOCKERFILES_PATH/web_vapt.Dockerfile --label branch=development --label commit_sha=$COMMIT_SHA --tag $DOCKER_REGISTRY/rajanagori/nightingale_web_vapt_image:development
    
    # - name: Push nightingale_web_vapt_image
    #   run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_web_vapt_image:development"
    
    - name: Build nightingale_network_vapt_image
      run: |
        docker build . --no-cache --file $DOCKERFILES_PATH/network_vapt.Dockerfile --label branch=development --label commit_sha=$COMMIT_SHA --tag $DOCKER_REGISTRY/rajanagori/nightingale_network_vapt_image:development
    
    # - name: Push nightingale_network_vapt_image
    #   run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_network_vapt_image:development"
    
    - name: Build nightingale_osint_image
      run: |
        docker build . --no-cache --file $DOCKERFILES_PATH/osint_tools.Dockerfile --label branch=development --label commit_sha=$COMMIT_SHA --tag $DOCKER_REGISTRY/rajanagori/nightingale_osint_tools_image:development
    
    # - name: Push nightingale_osint_image
    #   run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_osint_tools_image:development"
    
    - name: Build nightingale_mobile_vapt_image
      run: |
        docker build . --no-cache --file $DOCKERFILES_PATH/mobile_vapt.Dockerfile --label branch=development --label commit_sha=$COMMIT_SHA --tag $DOCKER_REGISTRY/rajanagori/nightingale_mobile_vapt_image:development
    
    # - name: Push nightingale_mobile_vapt_image
    #   run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_mobile_vapt_image:development"
    
    - name: Build nightingale_wordlist_image
      run: |
        docker build . --no-cache --file $DOCKERFILES_PATH/wordlist.Dockerfile --label branch=development --label commit_sha=$COMMIT_SHA --tag $DOCKER_REGISTRY/rajanagori/nightingale_wordlist_image:development
    
    # - name: Push nightingale_wordlist_image
    #   run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_wordlist_image:development"
    
    - name: Build nightingale_development_image
      run: |
        docker build . --no-cache --file Dockerfile --label branch=development --label commit_sha=$COMMIT_SHA --tag $DOCKER_REGISTRY/rajanagori/nightingale:development

    # - name: Push nightingale_development_image
    #   run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale:development"

    - name: Clean Docker build cache
      run: |
        docker buildx prune -f