name: List Docker Images

on:
  push:
    branches: [ development ]

jobs:
  clean_untagged_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_REGISTRY }}

      - name: List Untagged Docker Images
        id: list_untagged_images
        run: |
          untagged_images=$(docker images -q --filter "dangling=true")
          echo "::set-output name=untagged_images::$untagged_images"

      # - name: Delete Untagged Docker Images
      #   if: steps.list_untagged_images.outputs.untagged_images != ''
      #   run: |
      #     docker rmi $(echo "${{ steps.list_untagged_images.outputs.untagged_images }}")