name: Docker Image CI 

on:
  push:
    branches: [main]
    paths:
      - "Dockerfiles/*.Dockerfile"
      - "Dockerfile"
      - ".github/workflows/docker-image.yaml"
  pull_request:
    branches: [main]
    paths:
      - "Dockerfiles/*.Dockerfile"
      - "Dockerfile"
      - ".github/workflows/docker-image.yaml"

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKERFILES_PATH: Dockerfiles
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Github Login
      env:
        GITHUB_TOKEN: ${{secrets.TOKEN}}
      run: |
        echo "${{secrets.TOKEN}}" | docker login ghcr.io -u ${{secrets.USERNAME}} --password-stdin
    # Clear apt cache    
    - name: Clear apt cache
      run: sudo apt-get clean

    # Build Docker images
    - name: Build nightingale_programming_image
      run: |
        docker build . --no-cache --file $DOCKERFILES_PATH/programming_langauge.Dockerfile --label branch=stable --label owner=RAJANAGORI --tag $DOCKER_REGISTRY/rajanagori/nightingale_programming_image:stable
    # # Push Docker images
    - name: Push nightingale_programming_image
      run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_programming_image:stable"

    - name: Build nightingale_forensic_and_red_teaming
      run: |
        docker build . --no-cache --file $DOCKERFILES_PATH/forensics_and_redteam.Dockerfile --label branch=stable --label owner=RAJANAGORI --tag $DOCKER_REGISTRY/rajanagori/nightingale_forensic_and_red_teaming:stable
    
    - name: Push nightingale_forensic_and_red_teaming1
      run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_forensic_and_red_teaming:stable"
    
    - name: Build nightingale_web_vapt_image
      run: |
        docker build  . --no-cache --file $DOCKERFILES_PATH/web_vapt.Dockerfile --label branch=stable --label owner=RAJANAGORI --tag $DOCKER_REGISTRY/rajanagori/nightingale_web_vapt_image:stable
    
    - name: Push nightingale_web_vapt_image
      run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_web_vapt_image:stable"
    
    - name: Build nightingale_network_vapt_image
      run: |
        docker build . --no-cache --file $DOCKERFILES_PATH/network_vapt.Dockerfile --label branch=stable --label owner=RAJANAGORI --tag $DOCKER_REGISTRY/rajanagori/nightingale_network_vapt_image:stable
    
    - name: Push nightingale_network_vapt_image
      run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_network_vapt_image:stable"
    
    - name: Build nightingale_osint_image
      run: |
        docker build . --no-cache --file $DOCKERFILES_PATH/osint_tools.Dockerfile --label branch=stable --label owner=RAJANAGORI --tag $DOCKER_REGISTRY/rajanagori/nightingale_osint_tools_image:stable
    
    - name: Push nightingale_osint_image
      run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_osint_tools_image:stable"
    
    - name: Build nightingale_mobile_vapt_image
      run: |
        docker build . --no-cache --file $DOCKERFILES_PATH/mobile_vapt.Dockerfile --label branch=stable --label owner=RAJANAGORI --tag $DOCKER_REGISTRY/rajanagori/nightingale_mobile_vapt_image:stable
    
    - name: Push nightingale_mobile_vapt_image
      run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_mobile_vapt_image:stable"
    
    - name: Build nightingale_wordlist_image
      run: |
        docker build . --no-cache --file $DOCKERFILES_PATH/wordlist.Dockerfile --label branch=stable --label owner=RAJANAGORI --tag $DOCKER_REGISTRY/rajanagori/nightingale_wordlist_image:stable
    
    - name: Push nightingale_wordlist_image
      run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale_wordlist_image:stable"
    
    - name: Build nightingale_stable_image
      run: |
        docker build . --no-cache --file Dockerfile --label branch=stable --label owner=RAJANAGORI --tag $DOCKER_REGISTRY/rajanagori/nightingale:stable

    - name: Push nightingale_stable_image
      run: docker push "$DOCKER_REGISTRY/rajanagori/nightingale:stable"