name: Multi OS docker images  - arm64

on:
  push:
    branches: [main]
    paths:
      - "architecture/arm64/Dockerfiles/*.Dockerfile"
      - "architecture/arm64/Dockerfile"
      - ".github/workflows/multi-os-arm64.yaml"
  pull_request:
    branches: [main]
    paths:
      - "architecture/arm64/Dockerfiles/*.Dockerfile"
      - "architecture/arm64/Dockerfile"
      - ".github/workflows/multi-os-arm64.yaml"

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKERFILE: architecture/arm64
  DOCKERFILES_PATH: architecture/arm64/Dockerfiles
  IMAGE_NAME: ${{ github.repository }}\


jobs:
  arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Github Login
      env:
        GITHUB_TOKEN: ${{secrets.TOKEN}}
      run: |
        echo "${{secrets.TOKEN}}" | docker login ghcr.io -u ${{secrets.USERNAME}} --password-stdin
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Clean Docker build cache
      run: |
        docker buildx prune -f
      
    # Build Docker images
    - name: Build nightingale_programming_image
      run: |
        docker buildx build --push --platform linux/arm64 . --no-cache --file $DOCKERFILES_PATH/programming_langauge.Dockerfile --label branch=stable --label owner=RAJANAGROI --tag $DOCKER_REGISTRY/rajanagori/nightingale_programming_image:linux-arm64

    - name: Build nightingale_forensic_and_red_teaming
      run: |
        docker buildx build --push --platform linux/arm64 . --no-cache --file $DOCKERFILES_PATH/forensics_and_redteam.Dockerfile --label branch=stable --label owner=RAJANAGROI --tag $DOCKER_REGISTRY/rajanagori/nightingale_forensic_and_red_teaming:linux-arm64
    
    - name: Build nightingale_web_vapt_image
      run: |
        docker buildx build --push --platform linux/arm64  . --file $DOCKERFILES_PATH/web_vapt.Dockerfile --label branch=stable --label owner=RAJANAGROI --tag $DOCKER_REGISTRY/rajanagori/nightingale_web_vapt_image:linux-arm64

    - name: Build nightingale_network_vapt_image
      run: |
        docker buildx build --push --platform linux/arm64 . --no-cache --file $DOCKERFILES_PATH/network_vapt.Dockerfile --label branch=stable --label owner=RAJANAGROI --tag $DOCKER_REGISTRY/rajanagori/nightingale_network_vapt_image:linux-arm64

    - name: Build nightingale_osint_image
      run: |
        docker buildx build --push --platform linux/arm64 . --no-cache --file $DOCKERFILES_PATH/osint_tools.Dockerfile --label branch=stable --label owner=RAJANAGROI --tag $DOCKER_REGISTRY/rajanagori/nightingale_osint_tools_image:linux-arm64

    - name: Build nightingale_mobile_vapt_image
      run: |
        docker buildx build --push --platform linux/arm64 . --no-cache --file $DOCKERFILES_PATH/mobile_vapt.Dockerfile --label branch=stable --label owner=RAJANAGROI --tag $DOCKER_REGISTRY/rajanagori/nightingale_mobile_vapt_image:linux-arm64

    - name: Build nightingale_wordlist_image
      run: |
        docker buildx build --push --platform linux/arm64 . --no-cache --file $DOCKERFILES_PATH/wordlist.Dockerfile --label branch=stable --label owner=RAJANAGROI --tag $DOCKER_REGISTRY/rajanagori/nightingale_wordlist_image:linux-arm64

    - name: Build nightingale_linux-arm64_image
      run: |
        docker buildx build --push --platform linux/arm64 . --no-cache --file $DOCKERFILE/Dockerfile --label branch=stable --label owner=RAJANAGROI --tag $DOCKER_REGISTRY/rajanagori/nightingale:linux-arm64

    - name: Clean Docker build cache - amd64
      run: |
        docker buildx prune -f