name: Multi OS Docker Images - ARM64 macOS

on:
  push:
    branches: [development]
    paths:
      - "architecture/arm64/v8/Dockerfiles/*.Dockerfile"
      - "architecture/arm64/v8/Dockerfile"
      - ".github/workflows/multi-os-arm64.yaml"
  pull_request:
    branches: [development]
    paths:
      - "architecture/arm64/v8/Dockerfiles/*.Dockerfile"
      - "architecture/arm64/v8/Dockerfile"
      - ".github/workflows/multi-os-arm64.yaml"

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKERFILES_PATH: architecture/arm64/v8/Dockerfiles
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  arm64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - programming_langauge.Dockerfile
          - forensics_and_redteam.Dockerfile
          - web_vapt.Dockerfile
          - network_vapt.Dockerfile
          - osint_tools.Dockerfile
          - mobile_vapt.Dockerfile
          - wordlist.Dockerfile
          - ../Dockerfile # Adjust for additional Dockerfiles if needed

    steps:
    - uses: actions/checkout@v4

    - name: Validate Secrets
      run: |
        if [[ -z "${{ secrets.TOKEN }}" || -z "${{ secrets.USERNAME }}" ]]; then
          echo "Error: Missing registry credentials"
          exit 1
        fi

    - name: GitHub Login
      run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ secrets.USERNAME }} --password-stdin

    - name: Set Username to Lowercase
      run: |
        USERNAME_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        echo "USERNAME=$USERNAME_LOWER" >> $GITHUB_ENV

    - name: Clear apt cache
      run: sudo apt-get clean

    - name: Get Commit Hash
      id: vars
      run: echo "COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    - name: Validate Buildx Installation
      run: docker buildx ls

    - name: Debug Environment Variables
      run: |
        echo "Commit SHA: ${{ env.COMMIT_HASH }}"
        echo "Docker Registry: $DOCKER_REGISTRY"
        echo "Username: ${{ env.USERNAME }}"

    - name: Build and Push ARM64 Images
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ env.DOCKERFILES_PATH }}/${{ matrix.dockerfile }}
        platforms: linux/arm64/v8
        tags: |
          $DOCKER_REGISTRY/${{ env.USERNAME }}/${{ matrix.dockerfile }}:arm64-development
          $DOCKER_REGISTRY/${{ env.USERNAME }}/${{ matrix.dockerfile }}:${{ env.COMMIT_HASH }}
          $DOCKER_REGISTRY/${{ env.USERNAME }}/${{ matrix.dockerfile.replace('.Dockerfile', '') }}:arm64-development
          $DOCKER_REGISTRY/${{ env.USERNAME }}/${{ matrix.dockerfile.replace('.Dockerfile', '') }}:${{ env.COMMIT_HASH }}

    - name: Final Debug
      run: docker images