name: Trivy Scan

on:
  push:
    branches: [ "development" ]
    paths:
      - ".github/workflows/trivy.yml"
  pull_request:
    branches: [ "development" ]
    paths:
      - ".github/workflows/trivy.yml"

permissions:
  contents: read
  security-events: write

jobs:
  build:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GitHub Container Registry
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Verify Image Existence
        run: docker pull ghcr.io/rajanagori/nightingale:stable

      - name: Cache Trivy DB
        uses: actions/cache@v3
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy-db
          restore-keys: |
            ${{ runner.os }}-trivy-db

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.57.0/trivy_0.57.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.57.0_Linux-64bit.deb
          trivy --cache-dir ${HOME}/.cache/trivy

      - name: Run Trivy vulnerability scanner
        run: |
          export TRIVY_AUTH_URL="https://ghcr.io"
          export TRIVY_TOKEN=$GITHUB_TOKEN
          for i in {1..5}; do
            trivy image \
              --skip-dirs /home/wordlist \
              --skip-files home/tools_web_vapt/WhatWeb/plugins/IpToCountry.csv \
              --format sarif \
              --output trivy-results.sarif \
              --severity CRITICAL \
              ghcr.io/rajanagori/nightingale:stable && break || sleep 60
          done
      # - name: Run Trivy vulnerability scanner
      #   run: |
      #     export TRIVY_AUTH_URL="https://ghcr.io"
      #     export TRIVY_TOKEN=$GITHUB_TOKEN
      #     for i in {1..5}; do
      #       trivy image \
      #         --platform linux/arm64 \
      #         --skip-dirs /home/wordlist \
      #         --skip-files home/tools_web_vapt/WhatWeb/plugins/IpToCountry.csv \
      #         --format sarif \
      #         --output trivy-results.sarif \
      #         --severity CRITICAL \
      #         ghcr.io/rajanagori/nightingale:arm64-development && break || sleep 60
      #     done

      - name: Verify Trivy results file
        run: |
          if [ -f "trivy-results.sarif" ]; then
            echo "trivy-results.sarif file exists."
          else
            echo "trivy-results.sarif file does not exist. Exiting."
            exit 1
          fi

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'